### ISSUE TITLE
Download PDF Button not working

### ISSUE THREAD

**Issue by angad11121** [LambdaIITH/AIMS-Helper-Chrome#13]
**Describe the bug**
Download PDF should be using client-side generated HTML code, but actually uses the source reference.

**Screenshots**

![image](https://user-images.githubusercontent.com/50276105/91654635-167ef800-eac8-11ea-85d7-57bc0e9237f4.png)
User Side HTML code

<br /><br /><br />

![image](https://user-images.githubusercontent.com/50276105/91654650-43330f80-eac8-11ea-8685-673c394c7cb4.png)
src/table.html file (screenshot taken from Inspect Element)

<br /><br /><br />
![image](https://user-images.githubusercontent.com/50276105/91654655-59d96680-eac8-11ea-88ad-79f820c0177c.png)
src/table.js that uses 'getElementById("timetable")' actually refers to the table.html file which is empty and then causes a download of blank Timetable

**Comment by npalladium** [comment]
@angad11121, do you want to take up this issue?

**Comment by angad11121** [comment]
I tried at that time, but couldn't fix it. I've found a solution now. Will try to do so!

**Comment by RachitKeertiDas** [comment]
@angad11121 Do let us know if you can still reproduce this.
