### ISSUE TITLE
Throw error if used on other websites

### ISSUE THREAD

**Issue by npalladium** [LambdaIITH/AIMS-Helper-Chrome#5]
Currently the Extension quietly fails and returns an empty timetable if used on other websites. It should throw an error if the URL does not match.

**Comment by RachitKeertiDas** [comment]
We have now hidden the extension on websites not matching aims.iith.ac.in as of latest main. If required, we can also throw a error in the extension prompt if required. 

#16 or a modification of it will be needed for that.

**Comment by RachitKeertiDas** [comment]
On second thought,  I actually think the current solution should be fine. Chrome explicitly tells the user that the extension will not be able to access information, and not be usable if clicked on another side. 

Hence, I'm closing this for now. Feel free to reopen if you feel the current solution is inadequate/needs major improvements. @npalladium
